### ISSUE TITLE
[1.16.3] tagList not working?

### ISSUE THREAD

**Issue by Gbergz** [CodersDownUnder/Loot-Bag-Mod#10]
Minecraft Version: 1.16.3
Mod Version: 1.16.3-1.6

**Describe the bug**
Entering an entry to the taglist makes it still drop from lootbags.

**To Reproduce**
1. For example add "minecraft:slabs" to tagList
2. Restart game
3. Use Loot Bag
4. Slabs still dropping from bag.

**Expected behavior**
Slabs or any other tag item not dropping from bags anymore.

**Screenshots**
![image](https://user-images.githubusercontent.com/26634554/95861422-b4214480-0d61-11eb-80ee-f497bc5d779d.png)

**Additional context**
Any ideas?

**Comment by Trhod17** [comment]
Fixed and uploaded [https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3079502](https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3079502)

**Comment by Gbergz** [comment]
Thanks! But.. it appears to still not work with the updated verison.
AKA not blacklisting those tags. I'm still receiving slabs, stairs etc.
![image](https://user-images.githubusercontent.com/26634554/95930102-f41a1300-0dc5-11eb-92bd-e276b25c9b9b.png)

**Comment by Trhod17** [comment]
Fixed for real this time hopefully
[https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files](https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files)

Incase the new 1.6.1 file hasnt been approved by the time you look at it

[https://github.com/CodersDownUnder/Loot-Bag-Mod/releases/tag/1.16.3V1.6.1](https://github.com/CodersDownUnder/Loot-Bag-Mod/releases/tag/1.16.3V1.6.1)
