### ISSUE TITLE
[1.16.5] Blacklist, modlist, whitelist not working on newest rewrite update (v2.0.0).

### ISSUE THREAD

**Issue by Gbergz** [CodersDownUnder/Loot-Bag-Mod#21]
Minecraft Version: 1.16.5
Mod Version: [2.0.0](https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3302353)

**Describe the bug**
1. When adding entries to the blacklist, items still drop from the loot bag.
2. When adding entries to the whitelist while it is enabled, items that are not on the whitelist are still dropping.
3. When adding a mod to the modlist blacklist, they're still dropping.

(Taglist is working like expected.)

**To Reproduce**
1. Add items to blacklist, still dropping blacklisted item.
2. Enable the whitelist, add items to the whitelist- items that are not on the whitelist are still dropping.
3. Add mod to modlist blacklist, mod items still drop.
4. Done.

**Expected behavior**
That blacklist, modlist & whitelist works like previous update before rewrite.

**-** Gbergz

**Comment by Trhod17** [comment]
Fixed in V2.1.0 https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3303336

**Comment by Gbergz** [comment]
Thanks. Seem to have fixed most problems.

Though the Item Blacklist doesn't seem to work. Still getting dropped items that are very much present inside the blacklist. I've blacklisted all spawn eggs for example though they're still dropping. And I've blacklisted all Coral items from minecraft + they're still dropping.

After further investigation item blacklist doesn't seem to work at all.

This one:
```
["Black And White Lists"]
	#Use the whitelist
	enablewhitelist = false
	#BlackList (Syntax "minecraft or modid : item or block name"; example "minecraft:air" or "lootbagmod:lootbag")
	blacklist = []
```

**Comment by Trhod17** [comment]
Hopefully should have finally fixed this if my testing is correct this time! https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3304482

**Comment by Gbergz** [comment]
Instead of opening a new issue I'll post this here. 
Config doesn't work at all on servers, anything I configure doesn't work. Everything works fine in SP.

Edit: On version 2.1.1

**Comment by Trhod17** [comment]
Fixed in v2.2.0 https://www.curseforge.com/minecraft/mc-mods/loot-bag-mod/files/3309921 the whitelist/blacklist/modlist requires the player to have the same config since they are done on during game load, the taglist might work i servers i forgot to test that since thats done when the player first uses a lootbag and the moblist works on the server without the player needing the same list.
